version: '0.2.{build}'
skip_non_tags: true
branches:
  only:
    - main

configuration:
 - Release
init:
 - ps: Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG
before_build:
 - nuget restore
after_build:
 - del Bins\%CONFIGURATION%\*.runtimeconfig.dev.json
artifacts:
 - path: Bins\$(configuration)
   name: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_TAG_NAME)
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: 'v$(APPVEYOR_REPO_TAG_NAME): '
    description: ''
    auth_token:
      secure: zS77Q6KGqj/AHLA80Kfyv95pXNEVYDV9mXNj0XyHoraqX5mu225SGhpFwS9oQxIB
    artifact: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_TAG_NAME)
    force_update: true