version: $(APPVEYOR_REPO_TAG_NAME)
skip_non_tags: true

configuration:
 - Debug
 - Release
before_build:
 - nuget restore
after_build:
 - del Bins\$(configuration)\$(APPVEYOR_PROJECT_NAME).runtimeconfig.dev.json
artifacts:
 - path: Bins\$(configuration)
   name: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_TAG_NAME)-$(configuration)